spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:55000/groudina
    username: postgres
    password: postgres

game:
  app:
    web:
      jwt:
        secret: ababaeowenfowiefnwoeifnwe27358923745892735d1892372jc571023571d8923j5d192351234ffn1kj3fn13f2304fx293f20x3fj234f
        expiration-seconds: 3600
