spring:
  r2dbc:
    url: "r2dbc:h2:mem://testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;"
    generate-unique-name: true
logging:
  level:
    io.r2dbc.h2: INFO
game:
  app:
    web:
      jwt:
        secret: "f2cfjcfmjo48fh3o48fhc3m48fsyor8y2o348ru5283fcjh3m4hfcs8hif7qh34f834hfslcf382oc3f820hcm89hwfselfi82h043cf892mh4rmcf2ld2jk4872d50k3475k2d345" # при запуске в проде это свойство нужно переопределить
        expiration-seconds: 86400
        fast-authentication-enabled: true
